#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/volcano.h"
#include "images/startscreen.h"
#include "images/luffy.h"
#include "images/lavaimg.h"
#include "images/gameover.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  GAMEOVER
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  Player player = {
    .x = 120,
    .y = 125,
    .speed = 2,
    .width = LUFFY_WIDTH,
    .height = LUFFY_HEIGHT
  };

  Lava lava = {
    .x = randint(0,240),
    .y = 0,
    .speed = 1,
    .width = LAVAIMG_WIDTH,
    .height = LAVAIMG_HEIGHT
  };

  int seconds = 0;
  int level = 1;
  int highestLvl = 0;
  int frameCount = 0;

  char secondsChar[10];
  char levelChar[10];
  char highestLvlChar[10];

  int backgroundSet = 1;
  int gameOverSet = 1;
  

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    switch (state) {
      case START:
        waitForVBlank();
        drawFullScreenImageDMA(startscreen);
       
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          player.x = 120;
          player.y = 125;
          player.speed = 2;

          lava.x = randint(0,240);
          lava.y = 0;
          lava.speed = 1;
          
          seconds = 0;
          level = 1;
          frameCount = 0;

          backgroundSet = 1;
          gameOverSet = 1;

          state = PLAY;
        }
        break;
        
      case PLAY:
      waitForVBlank();
        if (backgroundSet) {
          drawFullScreenImageDMA(Volcano1);
          backgroundSet = 0;
        }
  
        // On Screen Texts
        drawString(5,180, "Time:", WHITE);
        drawString(20,180, "Level:", WHITE);

        sprintf(secondsChar, "%d", seconds);
        sprintf(levelChar, "%d", level);
      
        drawRectDMA(4, 180, 55, 10, BLACK);
        drawString(5, 212, secondsChar, WHITE);
      
        drawRectDMA(19, 180, 55, 10, BLACK);
        drawString(20,217, levelChar, WHITE);


        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        
         // Player Movement
        undrawImageDMA(player.y, player.x , player.width , player.height, Volcano1);
        if(!(BUTTON_RIGHT & currentButtons) && player.x < 215) {
          player.x += player.speed;
        }
        if(!(BUTTON_LEFT & currentButtons) && player.x > 0) {
          player.x -= player.speed;
        }
        drawImageDMA(player.y, player.x , player.width , player.height, luffy);
        
        //Lava Falling
        undrawImageDMA(lava.y, lava.x , lava.width , lava.height, Volcano1);
        lava.y += lava.speed;
        drawImageDMA(lava.y, lava.x , lava.width , lava.height, lavaimg);

        
        //Seconds and Level Implementation
        frameCount++;
        if (frameCount >= 60) {
          frameCount = 0;
          seconds++;
         
          if (seconds % 10 == 0) {
            level++;
            lava.speed++;
          }
        }
      
        //Collision Detection
        if (lava.x < player.x + player.width &&
            lava.x + lava.width > player.x &&
            lava.y < player.y + player.height &&
            lava.y + lava.height > player.y) {

            state = GAMEOVER;
            break;
           }

        if (lava.y >= 160) {
          lava.x = randint(0,240);
          lava.y = 0;
        }

        break;

      case GAMEOVER:
        waitForVBlank();

        if (gameOverSet) {
          drawFullScreenImageDMA(gameover);
          gameOverSet = 0;
        }
        if (level > highestLvl) {
          highestLvl = level;
          sprintf(highestLvlChar, "%d", highestLvl);
        }

        // Game Over Texts
        drawString(50,50, "Game Over", RED);
        drawString(75,50, "Final Level:", RED);
        drawString(100,50, "Highest Level:", RED);

        drawString(75, 125, levelChar, RED);
        drawString(100, 135, highestLvlChar, RED);
        
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }


  return 0;
}
